name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Go 1.21.4
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: SoundCloud Package
        run: go test pkg/soundcloud/* -v
      - name: Utils Package
        run: go test pkg/utils/* -v